[build]
  command = "npm run build"
  publish = ".vercel_static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = false # Only redirect if the file isn't found in the publish directory

[functions]
  included_files = ["build/server/**"]
